In [3]:
! wget -nc http://ai.stanford.edu/~amaas/data/sentiment/aclImdb_v1.tar.gz -P data
! tar -xzf data/aclImdb_v1.tar.gz -C data

File 'data/aclImdb_v1.tar.gz' already there; not retrieving.



In [4]:
!tree -dL 2 data/aclImdb

data/aclImdb
├── test
│   ├── neg
│   └── pos
└── train
    ├── neg
    ├── pos
    └── unsup

7 directories


In [2]:
!rm -r data/aclImdb/train/unsup


In [3]:
from sklearn.datasets import load_files


In [25]:
%matplotlib inline


# pip install mglearn # Note that for my new MacBook, I need to install this package.
import mglearn # https://github.com/amueller/introduction_to_ml_with_python/tree/master/mglearn
# from preamble import *

import numpy as np
# import matplotlib.pyplot as plt
import pandas as pd

from IPython.display import display



from sklearn.datasets import load_files

reviews_train = load_files("data/aclImdb/train/")
# load_files returns a bunch, containing training texts and training labels
text_train, y_train = reviews_train.data, reviews_train.target
print("type of text_train: {}".format(type(text_train)))
print("length of text_train: {}".format(len(text_train)))

print(20*"*")
for i in range(7):
    print(20*"*")
    print(f"text_train[{i}]:\n{text_train[i]}")
    print(20*"*")

type of text_train: <class 'list'>
length of text_train: 25000
********************
********************
text_train[0]:
b"Zero Day leads you to think, even re-think why two boys/young men would do what they did - commit mutual suicide via slaughtering their classmates. It captures what must be beyond a bizarre mode of being for two humans who have decided to withdraw from common civility in order to define their own/mutual world via coupled destruction.<br /><br />It is not a perfect movie but given what money/time the filmmaker and actors had - it is a remarkable product. In terms of explaining the motives and actions of the two young suicide/murderers it is better than 'Elephant' - in terms of being a film that gets under our 'rationalistic' skin it is a far, far better film than almost anything you are likely to see. <br /><br />Flawed but honest with a terrible honesty."
********************
********************
text_train[1]:
b'Words can\'t describe how bad this movie is. I can\'t

In [26]:
text_train = [doc.replace(b"<br />", b" ") for doc in text_train] # Replaces all the HTML line break tags.

In [18]:
print(20*"*")
for i in range(7):
    print(20*"*")
    print("text_train[i]:\n{}".format(text_train[i]))
    print(20*"*")

********************
********************
text_train[i]:
b"Zero Day leads you to think, even re-think why two boys/young men would do what they did - commit mutual suicide via slaughtering their classmates. It captures what must be beyond a bizarre mode of being for two humans who have decided to withdraw from common civility in order to define their own/mutual world via coupled destruction.  It is not a perfect movie but given what money/time the filmmaker and actors had - it is a remarkable product. In terms of explaining the motives and actions of the two young suicide/murderers it is better than 'Elephant' - in terms of being a film that gets under our 'rationalistic' skin it is a far, far better film than almost anything you are likely to see.   Flawed but honest with a terrible honesty."
********************
********************
text_train[i]:
b'Words can\'t describe how bad this movie is. I can\'t explain it by writing only. You have too see it for yourself to get at grip of how

In [27]:
type(text_train[0])

bytes

Should read documentation on strings and Unicode:  [Unicode](https://docs.python.org/3/howto/unicode.html

In [28]:
np.unique(y_train)

array([0, 1])

In [29]:
print("Samples per class (training): {}".format(np.bincount(y_train)))

Samples per class (training): [12500 12500]


In [30]:
reviews_test = load_files("data/aclImdb/test/")
text_test, y_test = reviews_test.data, reviews_test.target
print("Number of documents in test data: {}".format(len(text_test)))
print("Samples per class (test): {}".format(np.bincount(y_test)))
text_test = [doc.replace(b"<br />", b" ") for doc in text_test]

Number of documents in test data: 25000
Samples per class (test): [12500 12500]


### 7.3. Representing Text Data as a Bag of Words

In [31]:
bards_words =["The fool doth think he is wise,",
              "but the wise man knows himself to be a fool"]

In [32]:
from sklearn.feature_extraction.text import CountVectorizer
vect = CountVectorizer()
vect.fit(bards_words) # Labels every word in the vocabulary with a number.

CountVectorizer()

In [33]:
print("Vocabulary size: {}".format(len(vect.vocabulary_)))
print("Vocabulary content:\n {}".format(vect.vocabulary_))

Vocabulary size: 13
Vocabulary content:
 {'the': 9, 'fool': 3, 'doth': 2, 'think': 10, 'he': 4, 'is': 6, 'wise': 12, 'but': 1, 'man': 8, 'knows': 7, 'himself': 5, 'to': 11, 'be': 0}


In [34]:
# each sentence is turned into a bag of words (array) with the count of each word in the array listed in order based
# on the labels assigned by vect.vocabulary_.
bag_of_words = vect.transform(bards_words) 
print("bag_of_words: {}".format(repr(bag_of_words)))

bag_of_words: <2x13 sparse matrix of type '<class 'numpy.int64'>'
	with 16 stored elements in Compressed Sparse Row format>


In [35]:
print("Dense representation of bag_of_words:\n{}".format(
    bag_of_words.toarray()))

Dense representation of bag_of_words:
[[0 0 1 1 1 0 1 0 0 1 1 0 1]
 [1 1 0 1 0 1 0 1 1 1 0 1 1]]


### [Start here](https://github.com/amueller/introduction_to_ml_with_python/blob/master/07-working-with-text-data.ipynb) with input 14 (pp. 337 in the book).